### ISSUE TITLE
最近20次都失败，每次都出现keyError这样的问题，请问大佬怎么解决呢

### ISSUE THREAD

**Issue by xianyun579** [luzy99/SEUAutoLogin#26]
Run python ./dayReport.py -u *** -p ***
  python ./dayReport.py -u *** -p ***
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.13/x64/lib
[2](https://github.com/xianyun579/SEUAutoLogin/runs/7701288812?check_suite_focus=true#step:5:2)022-08-06 09:4[3](https://github.com/xianyun579/SEUAutoLogin/runs/7701288812?check_suite_focus=true#step:5:3):22.898969+08:00
Traceback (most recent call last):
  File "./dayReport.py", line 16[5](https://github.com/xianyun579/SEUAutoLogin/runs/7701288812?check_suite_focus=true#step:5:5), in <module>
    ss = login(configs['user']['cardnum'], configs['user']['password'])
  File "/home/runner/work/SEUAutoLogin/SEUAutoLogin/login.py", line 23, in login
    form['password'] = encryptAES(password, form['pwdDefaultEncryptSalt'])
KeyError: 'pwdDefaultEncryptSalt'
Error: Process completed with exit code 1.

**Comment by Sciroccogti** [comment]
请尝试根据 README 更新仓库
